# All values in no of frames
BACKGROUND_COLOR: gray
FRAME_RATE: 60

FIX_CROSS_TIME: 60 #1000ms
FIX_CROSS_COLOR: black
STIM_COLOR: black
STIM_TIME: 240 #4000ms as timeout
STIM_HEIGHT: 108 #0.1 x 1080
TEXT_HEIGHT: 40

NO_TRAINING_TRIALS: 15
NO_TRAINING2_TRIALS: 10

NO_BLOCKS: 4
NO_TRIALS: 50

REACTION_KEYS: ['a', 'k', 'A', 'K']

